version: "3"

services:
  wakanda_blockchain_cont:
    container_name: wakanda_blockchain_cont
    image: wakanda_blockchain_cont:latest
    build:
      context: .
      dockerfile: Dockerfile_wakanda_blockchain
    network_mode: host
  
  wakanda_api_cont:
    container_name: wakanda_api_cont
    image: wakanda_api_cont:latest
    build:
      context: .
      dockerfile: Dockerfile_wakanda_api
    network_mode: host
